site_name: 光尘
site_description: 技术分享
site_author: xiaopch
theme:
  name: material
  language: 'zh'
  custom_dir: custom_theme/
  highlightjs: true
#theme: readthedocs  material mkdocs
#markdown_extensions:
#  - admonition
#  - codehilite:
#      guess_lang: false
#      linenums: false
#  - toc:
#      permalink: true
#  - footnotes
#  - meta
#  - def_list
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.critic
#  - pymdownx.details
copyright: copyright@xiaopch
repo_url: https://gitee.com/xiaopch/xiaopch.git

#nav:
#  - Home: index.md
#  - Develoment: development.md
#  - About: about.md